version: 2

jobs:
  build:
    branches:
      ignore:
        - l10n_master
        - gh-pages
    working_directory: ~/code
    docker:
      - image: cimg/android:2021.10.2-node
    environment:
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process" -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "android/build.gradle.kts" }}
#      - run:
#          name: Run Lint
#          command: ./gradlew lint --warning-mode all
#      - store_artifacts:
#          path: android/build/reports
#          destination: reports
      - run:
          name: Run Debug Build
          command: ./gradlew assembleDebug --warning-mode all
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android/build-cache
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "android/build.gradle.kts" }}
      - store_artifacts:
          path: android/build/outputs/apk
          destination: apk
